### ISSUE TITLE
IDA 7.0 50% plugins not works

### ISSUE THREAD

**Issue by Karaulov** [devttys0/ida#17]
Please add 7.0 ida support. For example many plugins uses add_menu_item, need fix it.

**Comment by mzpqnxow** [comment]
Let me add some *useful* information.

Seems to be the issue described here where a deprecated menu API was eliminated: https://github.com/x64dbg/x64dbgida/issues/4

I don't know how to fix it properly to be honest but I will look when I have time. @devttys0 are you still maintaining these plugins? If so, I believe this will be a relatively simple fix for you. FYI, I have the error on (I think) every plugin starting with v7.

It's complaining that the idaapi module no longer has the `add_menu_item` and `del_menu_item` functions.

**Comment by mzpqnxow** [comment]
@devttys0 	this commit shows an example of a corrected version, if it is helpful:

https://github.com/techbliss/x64dbgida/commit/ad771308470ef193d140d029ad48064d8edd6270#diff-8a12517df172d99e71415f82dbd14766
