### ISSUE TITLE
standalone creation of riz signatures

### ISSUE THREAD

**Issue by somenet** [devttys0/ida#8]
Is it possible / this is a request for enhancement / to create riz signatures without having to load up IDA?

Basically the idea is to be able to create many signatures on systems without having to go the way to singlehandedly every file.
e.g. create riz-signatures of all my linux so files.

**Comment by devttys0** [comment]
Short answer is no, rizzo can't be used without IDA; it relies on IDA to do all the disassembly, function identification, xrefs, etc. that it needs to create signatures. Certainly this could be done with some other disassembly library (e.g., the Capstone library), but that would be a completely different tool.

However, you can run IDA in batch mode for automated processing of many files. In batch mode, you can tell IDA to run an IDAPython script, and that script can automatically invoke rizzo, something like this for example:

```python
import idc
import idaapi
import rizzo

# Wait for IDA to finish auto-analysis
idaapi.autoWait()
# Generate rizzo signatures, save to /tmp.output.riz
rizzo.RizzoBuild('/tmp/output.riz')
# Close IDA
idc.Exit(0)
```

Typically, you'd invoke IDA on the command line with something like:

```bash
$ idal -A -S myscript.py libuClibc.so
```

You can then just have a shell script loop through all the files you want to generate signatures for.

For more information on running IDA in batch mode, see:

https://www.hex-rays.com/products/ida/support/idadoc/417.shtml
http://www.hexblog.com/?p=53
http://www.codejury.com/idas-batch-mode/
